python feature_reduction.py uT 1 0.1 >> result
python feature_reduction.py uT 3 0.1 >> result
python feature_reduction.py uT 5 0.1 >> result
python feature_reduction.py uT 7 0.1 >> result
python feature_reduction.py uT 9 0.1 >> result
python feature_reduction.py uT 11 0.1 >> result
python feature_reduction.py uT 13 0.1 >> result
python feature_reduction.py uT 15 0.1 >> result
python feature_reduction.py uT 17 0.1 >> result
python feature_reduction.py uT 19 0.1 >> result
python feature_reduction.py uT 21 0.1 >> result
python feature_reduction.py uT 23 0.1 >> result
python feature_reduction.py uT 25 0.1 >> result
python feature_reduction.py uT 27 0.1 >> result
python feature_reduction.py uT 29 0.1 >> result
python feature_reduction.py uT 31 0.1 >> result
python feature_reduction.py uT 33 0.1 >> result
python feature_reduction.py uT 35 0.1 >> result
python feature_reduction.py uT 37 0.1 >> result
python feature_reduction.py uT 39 0.1 >> result
python feature_reduction.py uT 41 0.1 >> result
python feature_reduction.py uT 43 0.1 >> result
python feature_reduction.py uT 45 0.1 >> result
python feature_reduction.py uT 47 0.1 >> result
python feature_reduction.py uT 49 0.1 >> result
python feature_reduction.py uT 51 0.1 >> result
python feature_reduction.py uT 53 0.1 >> result
python feature_reduction.py uT 55 0.1 >> result
python feature_reduction.py uT 57 0.1 >> result
python feature_reduction.py uT 59 0.1 >> result
python feature_reduction.py uT 61 0.1 >> result
python feature_reduction.py uT 63 0.1 >> result
python feature_reduction.py uT 65 0.1 >> result
python feature_reduction.py uT 67 0.1 >> result
python feature_reduction.py uT 69 0.1 >> result
python feature_reduction.py uT 71 0.1 >> result
